plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

def protocolVersion = protocols_use_local_build == "true" ? protocols_local_version : protocols_version

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
    implementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}")
    api("me.shedaniel.cloth:cloth-config-fabric:${clothconfig_version}")

    implementation("com.github.NiFeather:feathermorph-protocols:$protocolVersion")
    implementation("me.shedaniel.cloth:cloth-config-fabric:${clothconfig_version}")
    api("com.terraformersmc:modmenu:${modmenu_version}")

    implementation("com.github.NiFeather:feathermorph-command-compat-layer:${compat_layer_version}")
    include("com.github.NiFeather:feathermorph-command-compat-layer:${compat_layer_version}")

    include("com.github.NiFeather:feathermorph-protocols:${protocolVersion}")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}