# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Mod Properties
maven_group=feathermorph
archives_base_name=feathermorph-client
java_version=25

mod_name=FeatherMorphClient
mod_author=MATRIX-feather
mod_id=feathermorph_client
version=0.18.0-alpha.1
license=MIT
credits=404
description=Client mod for the FeatherMorph plugin

# Minecraft Properties
minecraft_version=26.1
minecraft_version_range=[26.1]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
#parchment_minecraft=1.21.6
#parchment_version=2025.06.01
# Don't apply this

# Fabric
#fabric_version=0.133.12+1.21.9
#fabric_loader_version=0.17.2
#fabric_game_version_range=>1.21.8
fabric_version=0.144.3+26.1
fabric_loader_version=0.18.5
fabric_game_version_range=>=26.1

# NeoForge
neoforge_version=21.8.1-beta
neoforge_loader_version_range=[4,)
neoforge_version_range=[21,)

# Dependencies
# check this on https://modmuss50.me/fabric.html
modmenu_version=18.0.0-alpha.8
clothconfig_version=26.1.154

emf_version=QmjzUJ5G
etf_version=ZGRPXhJ6
paperdoll_version=iI5zaZQI

fabric_base = 0.4.42+f0c952b36c
fabric_networking = 4.3.2+2a3568d56c

# FM Protocols
compat_layer_version=1e9f6470d7
protocols_version=6e370dcfa88bd83496f255646cfc967da263c4f3
protocols_use_local_build=true
protocols_local_version=2.9.0
