# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Mod Properties
maven_group=feathermorph
archives_base_name=feathermorph-client
java_version=21

mod_name=FeatherMorphClient
mod_author=MATRIX-feather
mod_id=feathermorph_client
version=0.12.0
license=MIT
credits=404
description=Client mod for the FeatherMorph plugin

# Minecraft Properties
minecraft_version=1.21.6
minecraft_version_range=[1.21.6]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.6-20250617.151856
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
#parchment_minecraft=1.21.6
#parchment_version=2025.06.01
# Don't apply this

# Fabric
fabric_version=0.127.0+1.21.6
fabric_loader_version=0.16.14
fabric_game_version_range==1.21.6

# NeoForge
neoforge_version=21.6.0-beta
neoforge_loader_version_range=[4,)
neoforge_version_range=[21,)

# Dependencies
# check this on https://modmuss50.me/fabric.html
modmenu_version=15.0.0-beta.2
clothconfig_version=18.0.145

compat_layer_version=2e128d96ff
protocols_version=5cdc0ca682
protocols_use_local_build=false
protocols_local_version=2.1.1
